version: "3.8"

services:
  go-app:
    build:
      context: .
      target: go-dev
    container_name: go-app
    ports:
      - 8000:8000
    volumes:
      - .:/app
    networks:
      - appnet

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    networks:
      - appnet
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

networks:
  appnet:
